CREATE TABLE T_LS_USUARIO (
    cd_usuario INTEGER IDENTITY(1,1) NOT NULL,
    nm_usuario VARCHAR(100) NOT NULL,
    dt_nascimento DATE NOT NULL,
    ds_email VARCHAR(150) NOT NULL,
    nr_telefone CHAR(11),
    ds_senha VARCHAR(255) NOT NULL
);

ALTER TABLE T_LS_USUARIO 
    ADD CONSTRAINT PK_USUARIO PRIMARY KEY CLUSTERED (cd_usuario);

ALTER TABLE T_LS_USUARIO 
    ADD CONSTRAINT UN_USUARIO_EMAIL UNIQUE NONCLUSTERED (ds_email);

ALTER TABLE T_LS_USUARIO 
    ADD CONSTRAINT UN_USUARIO_FONE UNIQUE NONCLUSTERED (nr_telefone);



CREATE TABLE T_LS_PUBLICACAO (
    cd_publicacao INTEGER IDENTITY(1,1),
    cd_usuario INTEGER NOT NULL,
    dt_publicacao DATETIME NOT NULL,
    ds_publicacao NVARCHAR(255),
    ds_imagem VARCHAR(255),
    ds_video VARCHAR(255)
);

ALTER TABLE T_LS_PUBLICACAO 
    ADD CONSTRAINT PK_PUBLICACAO PRIMARY KEY CLUSTERED (cd_publicacao);



CREATE TABLE T_LS_TREINO (
    cd_treino INTEGER IDENTITY(1,1),
    cd_usuario INTEGER NOT NULL,
    nm_treino VARCHAR(100) NOT NULL,
    ds_treino VARCHAR(50) NOT NULL,
    tp_treino CHAR(1) NOT NULL
);

ALTER TABLE T_LS_TREINO 
    ADD CONSTRAINT PK_TREINO PRIMARY KEY CLUSTERED (cd_treino);

ALTER TABLE T_LS_TREINO 
    ADD CONSTRAINT CK_TREINO_TIPO CHECK (tp_treino IN ('A','C','H'));



CREATE TABLE T_LS_CATEGORIA (
    cd_categoria INTEGER IDENTITY(1,1),
    nm_categoria VARCHAR(100) NOT NULL,
    nv_dificuldade CHAR(1) NOT NULL
);

ALTER TABLE T_LS_CATEGORIA 
    ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY CLUSTERED (cd_categoria);

ALTER TABLE T_LS_CATEGORIA 
    ADD CONSTRAINT CK_CATEGORIA_NIVEL CHECK (nv_dificuldade IN ('A','B'));



CREATE TABLE T_LS_EXERCICIO (
    cd_exercicio INTEGER IDENTITY(1,1),
    cd_categoria INTEGER NOT NULL,
    nm_exercicio VARCHAR(100) NOT NULL,
    qt_series INTEGER NOT NULL,
    nr_repeticoes INTEGER NOT NULL,
    ds_video_demontracao VARCHAR(255),
    ds_imagem_demonstracao VARCHAR(255)
);

ALTER TABLE T_LS_EXERCICIO 
    ADD CONSTRAINT PK_EXERCICIO PRIMARY KEY CLUSTERED (cd_exercicio);



CREATE TABLE T_LS_INTERACAO (
    cd_interacao INTEGER IDENTITY(1,1),
    cd_usuario INTEGER NOT NULL,
    dt_interacao DATETIME NOT NULL,
    ds_interacao NVARCHAR(255),
    ds_imagem VARCHAR(255),
    ds_video VARCHAR(255)
);

ALTER TABLE T_LS_INTERACAO 
    ADD CONSTRAINT PK_INTERACAO PRIMARY KEY CLUSTERED (cd_interacao);



CREATE TABLE T_LS_GRUPO (
    cd_grupo INTEGER IDENTITY(1,1),
    nm_grupo VARCHAR(100) NOT NULL
);

ALTER TABLE T_LS_GRUPO 
    ADD CONSTRAINT PK_GRUPO PRIMARY KEY CLUSTERED (cd_grupo);



CREATE TABLE T_LS_INTERACAO_GRUPO (
    cd_interacao_grupo INTEGER IDENTITY(1,1),
    cd_grupo INTEGER NOT NULL,
    dt_interacao DATETIME NOT NULL,
    ds_interacao_grupo NVARCHAR(255),
    ds_imagem_grupo VARCHAR(255),
    ds_video_grupo VARCHAR(255)
);

ALTER TABLE T_LS_INTERACAO_GRUPO 
    ADD CONSTRAINT PK_INTERACAO_GRUPO PRIMARY KEY CLUSTERED (cd_interacao_grupo);



CREATE TABLE T_LS_CONEXAO (
    cd_conexao INTEGER IDENTITY(1,1),
    cd_usuario INTEGER NOT NULL,
    nm_playlist VARCHAR(60) NOT NULL,
    ds_link_conexao VARCHAR(255) NOT NULL,
    tp_plataforma CHAR(1) NOT NULL
);

ALTER TABLE T_LS_CONEXAO 
    ADD CONSTRAINT PK_CONEXAO PRIMARY KEY CLUSTERED (cd_conexao);

ALTER TABLE T_LS_CONEXAO 
    ADD CONSTRAINT CK_CONEXAO_TIPO CHECK (tp_plataforma IN ('S','D','Y'));



CREATE TABLE T_LS_AGENDA (
    cd_agenda INTEGER IDENTITY(1,1),
    cd_usuario INTEGER NOT NULL,
    qt_dias INTEGER NOT NULL,
    ds_anotacao NVARCHAR(255)
);

ALTER TABLE T_LS_AGENDA 
    ADD CONSTRAINT PK_T_LS_AGENDA PRIMARY KEY CLUSTERED (cd_agenda);



CREATE TABLE T_LS_ACOMPANHAMENTO (
    cd_nutri INTEGER IDENTITY(1,1),
    cd_usuario INTEGER NOT NULL,
    dt_nutri DATE NOT NULL
);

ALTER TABLE T_LS_ACOMPANHAMENTO 
    ADD CONSTRAINT PK_ACOMPANHAMENTO PRIMARY KEY CLUSTERED (cd_nutri);



CREATE TABLE T_LS_METRICA_CORPORAL (
    cd_metrica_corporal INTEGER IDENTITY(1,1),
    cd_nutri INTEGER NOT NULL,
    vl_peso DECIMAL(5,2),
    vl_altura DECIMAL(3,2),
    vl_taxa_basal INTEGER,
    vl_bf INTEGER
);

CREATE UNIQUE NONCLUSTERED INDEX IDX_ACOMPANHAMENTO_METRICA
    ON T_LS_METRICA_CORPORAL (cd_nutri);

ALTER TABLE T_LS_METRICA_CORPORAL 
    ADD CONSTRAINT PK_METRICA_CORPORAL PRIMARY KEY CLUSTERED (cd_metrica_corporal);



CREATE TABLE T_LS_REFEICAO (
    cd_refeicao INTEGER IDENTITY(1,1),
    cd_nutri INTEGER NOT NULL,
    dt_refeicao DATETIME NOT NULL
);

ALTER TABLE T_LS_REFEICAO 
    ADD CONSTRAINT PK_REFEICAO PRIMARY KEY CLUSTERED (cd_refeicao);



CREATE TABLE T_LS_ALIMENTO (
    cd_alimento INTEGER IDENTITY(1,1),
    nm_alimento VARCHAR(50) NOT NULL,
    tp_alimento CHAR(1) NOT NULL
);

ALTER TABLE T_LS_ALIMENTO 
    ADD CONSTRAINT PK_ALIMENTO PRIMARY KEY CLUSTERED (cd_alimento);



CREATE TABLE T_LS_INFORMACAO_NUTRICIONAL (
    cd_info_nutri INTEGER IDENTITY(1,1),
    cd_alimento INTEGER NOT NULL,
    tm_porcao INTEGER NOT NULL,
    vl_energetico DECIMAL(5,1),
    qt_carboidrato DECIMAL(4,1),
    qt_proteina DECIMAL(4,1),
    qt_acucar_total DECIMAL(4,1),
    qt_acucar_adicionado DECIMAL(4,1),
    qt_gordura_total DECIMAL(4,1),
    qt_gordura_saturada DECIMAL(4,1),
    qt_gordura_trans DECIMAL(4,1),
    qt_fibra DECIMAL(4,1),
    qt_sodio DECIMAL(5,1)
);

CREATE UNIQUE NONCLUSTERED INDEX IDX_ALIMENTO_INFORMACAO
    ON T_LS_INFORMACAO_NUTRICIONAL (cd_alimento);

ALTER TABLE T_LS_INFORMACAO_NUTRICIONAL 
    ADD CONSTRAINT PK_INFORMACAO_NUTRICIONAL PRIMARY KEY CLUSTERED (cd_info_nutri);



CREATE TABLE T_LS_TREINO_EXERCICIO (
    cd_treino INTEGER NOT NULL,
    cd_exercicio INTEGER NOT NULL
);

ALTER TABLE T_LS_TREINO_EXERCICIO
    ADD CONSTRAINT PK_TREINO_EXERCICIO PRIMARY KEY CLUSTERED (cd_treino, cd_exercicio);



CREATE TABLE T_LS_GRUPO_USUARIO (
    cd_grupo INTEGER NOT NULL,
    cd_usuario INTEGER NOT NULL
);

ALTER TABLE T_LS_GRUPO_USUARIO
    ADD CONSTRAINT PK_GRUPO_USUARIO PRIMARY KEY CLUSTERED (cd_grupo, cd_usuario);



CREATE TABLE T_LS_REFEICAO_ALIMENTO (
    cd_refeicao INTEGER NOT NULL,
    cd_alimento INTEGER NOT NULL,
    qt_alimento DECIMAL(5,1)
);

ALTER TABLE T_LS_REFEICAO_ALIMENTO
    ADD CONSTRAINT PK_REFEICAO_ALIMENTO PRIMARY KEY CLUSTERED (cd_refeicao, cd_alimento);



ALTER TABLE T_LS_PUBLICACAO
    ADD CONSTRAINT FK_USUARIO_PUBLICACAO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_TREINO
    ADD CONSTRAINT FK_USUARIO_TREINO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_INTERACAO
    ADD CONSTRAINT FK_USUARIO_INTERACAO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_CONEXAO
    ADD CONSTRAINT FK_USUARIO_CONEXAO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_AGENDA
    ADD CONSTRAINT FK_T_LS_AGENDA_T_LS_USUARIO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_ACOMPANHAMENTO
    ADD CONSTRAINT FK_USUARIO_ACOMPANHAMENTO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_EXERCICIO
    ADD CONSTRAINT FK_CATEGORIA_EXERCICIO
    FOREIGN KEY (cd_categoria)
    REFERENCES T_LS_CATEGORIA (cd_categoria);

ALTER TABLE T_LS_INTERACAO_GRUPO
    ADD CONSTRAINT FK_GRUPO_INTERACAO
    FOREIGN KEY (cd_grupo)
    REFERENCES T_LS_GRUPO (cd_grupo);

ALTER TABLE T_LS_METRICA_CORPORAL
    ADD CONSTRAINT FK_ACOMPANHAMENTO_METRICA
    FOREIGN KEY (cd_nutri)
    REFERENCES T_LS_ACOMPANHAMENTO (cd_nutri);

ALTER TABLE T_LS_REFEICAO
    ADD CONSTRAINT FK_ACOMPANHAMENTO_REFEICAO
    FOREIGN KEY (cd_nutri)
    REFERENCES T_LS_ACOMPANHAMENTO (cd_nutri);

ALTER TABLE T_LS_INFORMACAO_NUTRICIONAL
    ADD CONSTRAINT FK_ALIMENTO_INFORMACAO
    FOREIGN KEY (cd_alimento)
    REFERENCES T_LS_ALIMENTO (cd_alimento);

ALTER TABLE T_LS_TREINO_EXERCICIO
    ADD CONSTRAINT PF_TREINO_TREINO_EXERCICIO
    FOREIGN KEY (cd_treino)
    REFERENCES T_LS_TREINO (cd_treino);

ALTER TABLE T_LS_TREINO_EXERCICIO
    ADD CONSTRAINT PF_EXERCICIO_TREINO_EXERCICIO
    FOREIGN KEY (cd_exercicio)
    REFERENCES T_LS_EXERCICIO (cd_exercicio);

ALTER TABLE T_LS_GRUPO_USUARIO
    ADD CONSTRAINT PF_GRUPO_GRUPO_USUARIO
    FOREIGN KEY (cd_grupo)
    REFERENCES T_LS_GRUPO (cd_grupo);

ALTER TABLE T_LS_GRUPO_USUARIO
    ADD CONSTRAINT PF_USUARIO_GRUPO_USUARIO
    FOREIGN KEY (cd_usuario)
    REFERENCES T_LS_USUARIO (cd_usuario);

ALTER TABLE T_LS_REFEICAO_ALIMENTO
    ADD CONSTRAINT PF_REFEICAO_REFEICAO_ALIMENTO
    FOREIGN KEY (cd_refeicao)
    REFERENCES T_LS_REFEICAO (cd_refeicao);

ALTER TABLE T_LS_REFEICAO_ALIMENTO
    ADD CONSTRAINT PF_ALIMENTO_REFEICAO_ALIMENTO
    FOREIGN KEY (cd_alimento)
    REFERENCES T_LS_ALIMENTO (cd_alimento);
